name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to server
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem
        rsync -avz --delete --exclude 'node_modules' -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' ./dist/ root@49.232.129.64:/www/wwwroot/restful/
        ssh -i deploy_key.pem -o StrictHostKeyChecking=no root@49.232.129.64 'cd /www/wwwroot/restful/ && npm ci --production && pm2 restart rsf'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
